// src/shared/permissions.ts
export const permissions = [
  "VIEW_WORKSPACE",
  "MANAGE_WORKSPACE",
  "MANAGE_MEMBERS",
  "MANAGE_ROLES",
  "MANAGE_PERMISSIONS",
  "VIEW_CHANNEL",
  "CREATE_CHANNEL",
  "MANAGE_CHANNEL",
  "DELETE_CHANNEL",
  "SEND_MESSAGE",
  "EDIT_OWN_MESSAGE",
  "DELETE_OWN_MESSAGE",
  "MANAGE_MESSAGES",
  "ADD_REACTION",
  "CREATE_THREAD",
  "VIEW_BOTS",
  "CREATE_BOT",
  "MANAGE_BOT",
  "MANAGE_BOT_TOKEN",
  "VIEW_WEBHOOKS",
  "CREATE_WEBHOOK",
  "MANAGE_WEBHOOK",
  "DELETE_WEBHOOK",
  "VIEW_PROJECT",
  "CREATE_PROJECT",
  "MANAGE_PROJECT",
  "VIEW_BOARD",
  "CREATE_BOARD",
  "MANAGE_BOARD",
  "CREATE_TASK",
  "MANAGE_TASK",
  "VIEW_MONITORING",
  "MANAGE_MONITORING",
  "VIEW_AUDIT_LOG",
  "MANAGE_SECURITY",
  "MANAGE_FEATURE_FLAGS",
  "MANAGE_PAGES",
  "VIEW_PAGES",
  "MANAGE_EMOJIS",
] as const;
export type Permission = (typeof permissions)[number];
export const memberPermissions: Permission[] = [
  "CREATE_THREAD",
  "VIEW_WORKSPACE",
  "VIEW_CHANNEL",
  "SEND_MESSAGE",
  "EDIT_OWN_MESSAGE",
  "DELETE_OWN_MESSAGE",
  "ADD_REACTION",
  "VIEW_PROJECT",
  "VIEW_BOARD",
  "CREATE_TASK",
  "MANAGE_TASK",
  "VIEW_PAGES",
];
export function permits(granted: readonly string[], permission: Permission) {
  return granted.includes(permission);
}
