// src/client/types.ts
export type Row = {
  id: string;
  event_types?: string[];
  avatar?: string;
  author_avatar?: string;
  mentions?: { id: string; kyros_user_id: string; name: string }[];
  participants?: string[];
  attachment_ids?: string[];
  user_ids?: string[];
  detail?: { fields: string[] };
  is_private?: boolean;
  is_dm?: boolean;
  pinned_at?: string;
  thread_id?: string;
  reply_count?: number;
  channel_name?: string;
  archived: boolean;
  name: string;
  title: string;
  description: string;
  content: string;
  type: string;
  kind: string;
  state: string;
  status: string;
  channel_id: string;
  category_id: string | null;
  project_id: string | null;
  column_id: string;
  board_id: string;
  position: number;
  priority: string;
  tags: string[];
  assignee: string | null;
  due_at: string | null;
  checklist: { text: string; done: boolean }[];
  links: { label: string; url: string }[];
  created_at: string;
  updated_at: string;
  edited_at: string | null;
  author_name: string;
  author_kind: string;
  user_id: string;
  technical_id: string;
  reply_to: string | null;
  reactions: { emoji: string; actor_id: string }[];
  permissions: string[];
  revoked: boolean;
  allow_tasks: boolean;
  role_id: string;
  role_name: string;
  is_owner: boolean;
  kyros_user_id: string;
  enabled: boolean;
  key: string;
  url: string;
  action: string;
  actor: string;
  target: string;
  last_checked_at: string;
  last_heartbeat: string;
  latency_ms: number | null;
  history: {
    state: string;
    latency_ms: number;
    created_at: string;
    detail: string;
  }[];
  blocks: { id?: string; type: string; content: string; checked?: boolean }[];
  revision: number;
  body: string;
  user_agent: string;
  current: boolean;
  last_seen_at: string;
  expires_at: string;
  mime: string;
  size: number;
  attachment_id: string;
  attempts: number;
  last_error: string;
  source: string;
  payload: Record<string, unknown>;
};
export type User = {
  avatar?: string;
  id: string;
  archived: boolean;
  name: string;
  kyros_user_id: string;
  bio: string;
  status: string;
  preferences: Record<string, string | boolean>;
};
export type Workspace = {
  id: string;
  archived: boolean;
  name: string;
  description: string;
  permissions: string[];
  role_name: string;
};
export type Result = {
  data: Row[];
  nextCursor?: string | null;
  permissions?: string[];
  deliveries?: Row[];
};
